spring:
  application:
    name: eureka-server

server:
  port: 9091

eureka:
  instance:
    hostname: eureka-9091.com
    instance-id: eureka-9091
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-9090.com:9090/eureka, http://eureka-9092.com:9092/eureka
