spring:
  application:
    name: consumer-service-feign

server:
  port: 9001

eureka:
  instance:
    hostname: consumer-service-feign-9001
  client:
    service-url:
      defaultZone: http://eureka-server-7000:7000/eureka

# 开启feign 熔断器
feign:
  hystrix:
    enabled: true
