spring:
  application:
    name: provider-service
  zipkin:
    base-url: http://localhost:8080

server:
  port: 8000

eureka:
  instance:
    hostname: provider-service-8000
  client:
    service-url:
      defaultZone: http://eureka-server-7000:7000/eureka
