spring:
  application:
    name: eureka-server

server:
  port: 9090

eureka:
  instance:
    hostname: eureka-9090.com
    instance-id: eureka-9090
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-9091.com:9091/eureka, http://eureka-9092.com:9092/eureka


