# 使用config 配置中心, 其他的微服也是一样，指定远端的配置文件即可
spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka-service #配置中心文件名称
      label: master
      profile: dev

