spring:
  application:
    name: mscloud.consumer-dept.com

server:
  port: 8089

eureka:
  instance:
    instance-id: mscloud.consumer-dept.com
  client:
    service-url:
      defaultZone: http://eureka-9090.com:9090/eureka, http://eureka-9091.com:9091/eureka, http://eureka-9092.com:9092/eureka
    register-with-eureka: false



