apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscloud-config
  labels:
    app: mscloud-config
    project: mscloud
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscloud-config
      project: mscloud
  template:
    metadata:
      labels:
        app: mscloud-config
        project: mscloud
        version: v1
    spec:
      containers:
      - name: config
        image: xiliangma/mscloud-config:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: dev
          containerPort: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mscloud/config
          name: config-data
      volumes:
      - name: config-data
        hostPath:
          path: /tmp/mscloud/config

---
apiVersion: v1
kind: Service
metadata:
  name: mscloud-config-service
  labels:
    app: mscloud-config
    project: mscloud
spec:
  selector:
    app: mscloud-config
    project: mscloud
  ports:
  - name: dev
    port: 8888
