apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscloud-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscloud-zuul
      project: mscloud
  template:
    metadata:
      labels:
        app: mscloud-zuul
        project: mscloud
    spec:
      containers:
      - name: zuul
        image: xiliangma/mscloud-zuul:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: dev
          containerPort: 5000
          hostPort: 30005
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mscloud/zuul
          name: zuul-data
      volumes:
      - name: zuul-data
        hostPath:
          path: /tmp/mscloud/zuul
---
apiVersion: v1
kind: Service
metadata:
  name: mscloud-zuul-service
  labels:
    app: mscloud-zuul
    project: mscloud
spec:
  selector:
    app: mscloud-zuul
    project: mscloud
  ports:
  - name: dev
    port: 5000
