apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscloud-zipkin
  labels:
    app: mscloud-zipkin
    project: mscloud
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscloud-zipkin
      project: mscloud
  template:
    metadata:
      labels:
        app: mscloud-zipkin
        project: mscloud
        version: v1
    spec:
      containers:
      - name: zipkin
        image: xiliangma/mscloud-zipkin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: dev
          containerPort: 3000
        - name: web
          containerPort: 8080
          hostPort: 30013
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - mountPath: /mscloud/zipkin
          name: zipkin-data
      volumes:
      - name: zipkin-data
        hostPath:
          path: /tmp/mscloud/zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: mscloud-zipkin-service
  labels:
    app: mscloud-zipkin
    project: mscloud
spec:
  selector:
    app: mscloud-zipkin
    project: mscloud
  ports:
  - name: dev
    port: 3000
  - name: web
    port: 8080