kind: ConfigMap
apiVersion: v1
metadata:
  name: mscloud-reload-demo
data:
  bootstrap.yml: |-
    config:
      message: This is default config!
    ---
    spring:
      profiles: dev
    config:
      message: This is dev config!
    ---
    spring:
      profiles: prod
    config:
        message: This is prod config!