spring:
  application:
    name: eureka-server

server:
  port: 9092

eureka:
  instance:
    hostname: eureka-9092.com
    instance-id: eureka-9092
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-9090.com:9090/eureka, http://eureka-9091.com:9091/eureka
